app = "ncsh-dashboard"
primary_region = "iad"  # virginia region

[build]
  dockerfile = "Dockerfile"

[env]
  PYTHONUNBUFFERED = "1"
  PYTHONPATH = "/app"
  PARQUET_FILE = "/app/data/data.parquet"
  AUTH_FLASK_ROUTES = "true"  # Enable Auth0 authentication
  ENVIRONMENT = "production"  # Set to production for Sentry reporting
  # Auth0 configuration
  AUTH0_CLIENT_ID = "J5SWYsyVTwGHZlnSPXoRQBh5F9JK3qUK"
  AUTH0_DOMAIN = "dev-0e4v07vo.auth0.com"
  AUTH0_CALLBACK_URL = "https://ncsh-dashboard.fly.dev/login/callback"
  # These should be set as secrets
  # AUTH0_CLIENT_SECRET = "${AUTH0_CLIENT_SECRET}"
  # APP_SECRET_KEY = "${APP_SECRET_KEY}"
  # ANTHROPIC_API_KEY = "${ANTHROPIC_API_KEY}"

[mounts]
  source = "litefs"
  destination = "/app/data"

[http_service]
  internal_port = 8050
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.headers]]
    for = "/*"
    [http_service.headers.values]
      X-Forwarded-Proto = "https"
      Strict-Transport-Security = "max-age=31536000; includeSubDomains"

  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 2048

[deploy]
  strategy = "immediate"
  release_command = ""

# Health check configuration
[metrics]
  port = 8050
  path = "/"

# Remove the duplicate service definition
# The http_service above will handle both HTTP and HTTPS