name: Deploy to Fly.io

on:
  push:
    branches:
      - main

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  S3_BUCKET: ${{ secrets.S3_BUCKET }}
  AWS_REGION: us-east-2  # Change this to your AWS region

jobs:
  verify_version:
    name: Verify version change
    runs-on: ubuntu-latest
    outputs:
      should_deploy: ${{ steps.check_version.outputs.changed }}
      new_version: ${{ steps.check_version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Fetch the last two commits to compare changes

      - name: Check if version changed
        id: check_version
        run: |
          # Get the latest version from current CHANGELOG
          NEW_VERSION=$(grep -m 1 "## \[" CHANGELOG.md | sed 's/## \[\(.*\)\].*/\1/')

          # Get the previous version by checking the previous commit
          OLD_VERSION=$(git show HEAD^:CHANGELOG.md | grep -m 1 "## \[" | sed 's/## \[\(.*\)\].*/\1/' || echo "none")

          if [ "$NEW_VERSION" != "$OLD_VERSION" ]; then
            echo "New version detected: $NEW_VERSION (was: $OLD_VERSION)"
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
          else
            echo "No version change detected"
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
          fi

  deploy:
    name: Deploy app
    needs: verify_version
    if: needs.verify_version.outputs.should_deploy == 'true'
    runs-on: ubuntu-latest
    environment: main
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::YOUR_ACCOUNT_ID:role/github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ env.AWS_SESSION_TOKEN }}

      - name: Create LiteFS volume if not exists
        run: |
          if ! flyctl volumes list | grep -q "litefs"; then
            flyctl volumes create litefs --size 10
          fi
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Configure Consul
        run: flyctl consul attach
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Create deployment tag
        run: |
          git tag -a "v${{ needs.verify_version.outputs.new_version }}" -m "Release ${{ needs.verify_version.outputs.new_version }}"
          git push origin "v${{ needs.verify_version.outputs.new_version }}"