name: Deploy to Fly.io

on:
  push:
    branches:
      - main
    paths:
      - 'CHANGELOG.md'

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  verify_version:
    name: Verify version change
    runs-on: ubuntu-latest
    outputs:
      should_deploy: ${{ steps.check_version.outputs.changed }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Fetch the last two commits to compare changes

      - name: Check if version changed
        id: check_version
        run: |
          if git diff HEAD^ HEAD -- CHANGELOG.md | grep -q '^\+## \['; then
            echo "Version change detected in CHANGELOG.md"
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "No version change in CHANGELOG.md"
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

  deploy:
    name: Deploy app
    needs: verify_version
    if: needs.verify_version.outputs.should_deploy == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Create LiteFS volume if not exists
        run: |
          if ! flyctl volumes list | grep -q "litefs"; then
            flyctl volumes create litefs --size 10
          fi
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Configure Consul
        run: flyctl consul attach
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}